// import { Inter } from "next/font/google";
import "./globals.css";
// import { SpeedInsights } from "@vercel/speed-insights/next"
import Navbar from '@/components/navbar'
import { Providers } from "./Providers";
import Footer from '@/components/footer'
import About from "./about/page";
// import type { Metadata } from "next";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PortFolio Prathmesh Gatade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-bdark bg-gray dark:text-txt">
        <Providers>
        <div className="z-10"><Navbar /></div>
        <div className="mt-[5%] -z-10">{children}</div>
        <div><Footer/></div>
        </Providers>
        
      </body>
    </html>
  );
}
